### ISSUE TITLE
Will you be adding a license?

### ISSUE THREAD

**Issue by hartmannr76** [JetBrains/teamcity-pipelines-dsl#1]
I've been building something very similar (since I'm a big fan of the Jenkins DSL and think the TeamCity one has great potential) and was wondering if you either have a roadmap and if you'd be able to add a license so we can extend this repo accordingly to work with our needs.

**Comment by antonarhipov** [comment]
@hartmannr76 sorry for delayed response. Yes, the license is added. Though, we are just experimenting here atm and planning to add this as a feature into the TeamCity DSL implementation.
