### ISSUE TITLE
Publish new pom.xml that has the https endpoint?

### ISSUE THREAD

**Issue by jfbibeau** [JetBrains/teamcity-pipelines-dsl#2]
Hi @antonarhipov - 

When trying to apply this dependency in our pom.xml, our TeamCity server fails to resolve the dependency with a handshake failure:

```
Failed to apply changes from VCS to project settings
Received fatal alert: handshake_failure. Please fix the errors in VCS and commit again.
```

Any chance this is due to the pom.xml having http instead of https? Can you republish 0.8 as 0.8.1 with the new POM you committed to see if this resolves the issue?

**Comment by antonarhipov** [comment]
@jfbibeau Hi! Sorry, for the delayed response. I have made the change some time ago already but didn't notify. There' s a 0.10 now and I'm actively experimenting with this approach. So keep in mind that the library isn't very stable yet.
